evaluate:
  mode: offline
  split: 0.2
train:
  age_bucket: 10
  data_path: data-pull/data/
  mid_rating_watch_over: 0.5
  num_warm_users: 10000
  pipeline_version: v1.0
  tag: Updated_Model
  train_for_prod: true
