evaluate:
  mode: offline
  split: 0.2
prepare:
  n_days: 5
train:
  age_bucket: 10
  data_path: data-pull/data/
  mid_rating_watch_over: 0.5
  pipeline_version: v1.0
  tag: Updated Model
  train_for_prod: true
